// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCebQOSqti0s0EiEZe_jdp2zRReNWZMY1E',
    appId: '1:5478165842:web:f4cfdcaf4e6111b4529e8b',
    messagingSenderId: '5478165842',
    projectId: 'chatterbox-f0556',
    authDomain: 'chatterbox-f0556.firebaseapp.com',
    storageBucket: 'chatterbox-f0556.appspot.com',
    measurementId: 'G-T0QLQ28507',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5A30e3TOqbSFT42BCrTH9W90WAvAVYos',
    appId: '1:5478165842:android:9c5b581759a1abee529e8b',
    messagingSenderId: '5478165842',
    projectId: 'chatterbox-f0556',
    storageBucket: 'chatterbox-f0556.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCsWGoR0YfhlHn4Z7S9lyI7f0rWVNUUzc',
    appId: '1:5478165842:ios:94dc954010632d54529e8b',
    messagingSenderId: '5478165842',
    projectId: 'chatterbox-f0556',
    storageBucket: 'chatterbox-f0556.appspot.com',
    iosBundleId: 'com.example.chatterbox',
  );
}
